service: language-roulette-api

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  profile: personal
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - 'iot:DescribeEndpoint'
      Resource: "*"
    - Effect: "Allow"
      Action:
        - 'sts:AssumeRole'
      Resource: "*"

functions:
  token:
    handler: handler.token
    events:
      - http:
          path: token
          method: get
          cors: true

  rooms:
    handler: handler.rooms
    events:
      - http:
          path: rooms
          method: get
          cors: true

  create-room:
    handler: handler.createRoom
    events:
      - http:
          path: rooms
          method: post
          cors: true

  auth:
    handler: handler.auth
    events:
      - http:
          path: auth
          method: get
          cors: true
    memorySize: 128
    timeout: 10

package:
  exclude:
    - .git/**
    - bin/**
    - README.md
